akathedeveloper/CareSync

CODE_OF_CONDUCT.md

**📌 Purpose**
Adds a well-structured CODE_OF_CONDUCT.md file to the CareSync repository, defining community standards, 
contributor expectations, and reporting guidelines in alignment with the values of GSSoC'25.
Related Issue
Fixed #1 
**🔧 Type of Change**
- [  ] Bug fix (non-breaking change)
- [  ] New feature
- [  ] Breaking change
**✅ How Has This Been Tested?**
- This is a documentation-only change and does not require execution or testing.
- Verified successful commit and push via Git command-line interface on Windows.
- **Environment Details:**
1. OS: Windows 10
2. Terminal: Command Prompt (Git Bash)
3. Git version: 2.xx
4. Browser: Chrome (for GitHub interface)
**📸 Screenshots** 
**📊 Impact / Performance**
- No performance impact
- No new dependencies introduced
- Adds a clear …

Add CODE_OF_CONDUCT.md for | GSSoC'25 Documentation

---

src/App.jsx
src/components/common/Sidebar.jsx

This PR addresses two main issues in the prescription module:
1. Sidebar responsiveness:
- Added a toggle arrow button on the left edge for small screens.
- On mobile, the sidebar slides out as an overlay when the arrow is tapped, and can be easily closed.
- On larger screens, the sidebar remains always visible and does not overlap the header or page title.
- This improves navigation clarity and accessibility across all device sizes.
2. Layout and routing fix:
- Updated routing to use nested routes where Layout acts as the parent route.
- Page components are now rendered as children routes inside the Layout using React Router’s <Outlet /> instead of passing children directly.
- This ensures the correct rendering of page content and resolves the issue of blank pages.
These changes enhance …

#16 Making sidebar responsive and Children-Outlet Mismatch 

---

src/pages/LandingPage.jsx

*Fix Footer Navigation Links**
Fixed footer navigation links to ensure proper routing throughout the application.
- Updated footer navigation references to use correct routing paths
- Improved user navigation experience

fix: update footer navigation links

---

src/pages/ContactUs.jsx
src/pages/Footer.jsx
src/pages/LandingPage.jsx

Refactored the navbar links and Contact Us component to improve layout, spacing, and scrolling behavior.  
- Fixed spacing between navbar items.  
- Ensured “Contact” link scrolls correctly to the Contact Us form.  
- Updated Contact Us component for proper padding and responsive height.  
- Improved hover underline for navbar links.
Fixes #93
---
- Extracted Contact Us section into a separate, reusable component.
- Updated routing/layout so the new component is properly displayed.
- Kept styling consistent with the existing design system.
- Enhanced footer with:
- Better spacing and alignment
- Updated links and social media icons
- Improved responsiveness for mobile
---
_Before:_ Navbar links uneven, ContactUs scroll behind navbar  
_After:_ Even spacing, ContactUs scrolls correctly …

Refactor: Separate Contact Us from Footer & Improve Footer design #93

---

src/App.jsx
src/pages/AboutPage.jsx

Hello @akathedeveloper ,
📝 Description
Added a comprehensive About Us page for CareSync healthcare platform featuring modern animations, interactive elements, and healthcare-focused design. The page provides detailed information about the company's mission, values, team, and journey while maintaining consistency with the existing design system and brand identity.
🔗 Related Issue(s)
issue #94 
https://github.com/user-attachments/assets/34b014e9-e4e3-4ca8-8539-c6ef6ed0f1ed
📋 Changes Made
1. Created comprehensive About Us page with 7 distinct sections including hero, mission/vision, stats, values, team, timeline, and contact CTA
2. Implemented advanced animations using Framer Motion with scroll-triggered effects, hover states, and smooth transitions
3. Added interactive statistics section …

Issue #94:About Us Page Added

---

src/components/common/navbar.jsx
src/pages/LandingPage.jsx

Successfull Made the Navbar Componenet to dont make this componenet again and again

Navbar componenets made

---

src/components/pharmacist/Inventory.jsx
src/components/pharmacist/PharmacistDashboard.jsx
src/components/pharmacist/Prescriptions.jsx

This pull request enhances the **Inventory** and **Prescriptions** components with new interactive features and dark mode support.  
The updates improve usability by adding **search functionality, modals, and stock indicators**.
---
Fixes #149 
---
---
1. **Search Bar:** Added a real-time medicine filter by name.  
2. **Update Stock Modal:** Clicking the "Update" button opens a modal to adjust stock quantities (simulated).  
3. **Low Stock Indicator:** Displays an icon + "Low" text for medicines below a set threshold (e.g., 50).  
4. **Dark Mode Support:** Styled with Tailwind CSS to ensure consistent appearance in both light and dark modes.  
1. **Search Bar:** Added filtering by patient name, doctor’s name, or prescription ID.  
2. **Completed List View:** Separated prescriptions into …

feat: Add enhancements to pharmacist dashboard and components

---

src/pages/ContactUs.jsx

Contact page has been updated
Fixes #148 
---
1.  UI has been enhanced for both dark and light mode
2.  Responsive
3. 
---
---
---

contact page updated

---

src/pages/Footer.jsx

Footer resposnivness fixed

---

src/components/common/Settings.jsx
src/contexts/AuthContext.jsx
src/firebase.js

Created the working setting feature and can update details
1. Added the setting feature in the project
2. USer can update and add details about themselves
3. data are link with backend 
Fixes #119 
---
1. Added the setting feature in the project
2. USer can update and add details about themselves
3. data are link with backend 
---
---
---
data are update or change in thebackend i.e firebase . correct the UID issue in the project

Created the working setting feature and can update details

---

src/components/common/Navbar.jsx

Fix of bug, that by clicking on logo user was not redirect to home page
Fixes #
---
1. Added a href link to home page
- [-] Documentation has been updated (if applicable)
- [-] I have checked for and resolved merge conflicts

fix retrun to home by logo

---

src/App.jsx
src/pages/CookiePolicy.jsx
src/pages/Footer.jsx
src/pages/GDPRCompliance.jsx

Hello @akathedeveloper,
I’ve added the Cookie Policy and GDPR Compliance pages. Please attach the appropriate labels to this PR and let me know if any changes are needed. (issue #169)
https://github.com/user-attachments/assets/c40b7a26-9e53-4537-8ac3-17f7801b51f9

Issue#169:Added Cookie Policy and GDPR compliance pages

---

src/components/common/Messages.jsx
src/pages/Notifications.jsx

Added the feature of message soo that the doctor can talk to users.
with the floating message and this is responsive, so that it could be easy for users.
Fixes #131 
---
1. Added the message section over there
2.  made the message section with the floating message section
3. users can message and share the details with others
4. users can use the feature of audio call and video call
---
---
---

Added the feature of message soo that the doctor can talk to users.

---

src/pages/auth/Register.jsx

I have added custom Js form validation for register form
Fixes #187 
---
1. Custom JavaScript Validation Improvements 
2. Add real-time validation (on input/blur) instead of only after submit.
3. Show styled error messages just below each invalid field.
4.Use red text/icons for errors and green checks for valid inputs.
5.Ensure consistent UI/UX with the existing form design.
---
---
---
---

ADD Feat: Custom JS form Validation for register form

---

src/components/pharmacist/Prescriptions.jsx

Reverts akathedeveloper/CareSync#241

Revert "Add confirmation dialog before deleting records"

---

src/App.jsx
src/pages/Footer.jsx
src/pages/License.jsx
src/pages/TermsOfServices.jsx

Added **Terms of Service** and **License** pages, designed to align with the existing website layout and styling. These pages ensure that the website includes essential legal and compliance information while maintaining a consistent user experience.  
Fixes #190   
---  
1. Created **Terms of Service** page following the existing site’s design system.  
2. Added **License** page with consistent UI and formatting.  
3. Updated navigation to include links to the new pages.  
---  
---  
https://github.com/user-attachments/assets/ca5061ae-9908-425a-b9af-be466d5c5360
---  
- Pages follow the existing design patterns for consistency.  
- Content is placeholder and can be updated later with finalized legal text if needed.  
Ready for Review @akathedeveloper

Pages: Create Terms and License Pages

---

src/pages/ContactUs.jsx

Link https://caresync-gssoc.vercel.app/ 
Issue No- #252
-🎨 UI/UX Improvement
---
1. Add height h-12 in Input field for Email Address
2. Add height h-12 in Subscribe button under input field
3. Add height h-12 in send message button under Text field
---
- [✅] My code follows the project’s coding guidelines
- [✅] I have tested these changes locally
- [✅ ] Documentation has been updated (if applicable)
- [✅ ] No new warnings or errors introduced
- [✅
I have checked for and resolved merge conflicts
---
Before
After
---

Change the input field size and button size #252

---

src/pages/LandingPage.jsx

Fixes #251 
---
1. 
2. 
3. 
---
---
---

Make the heading dynamic

---

src/pages/StatsSection.jsx

- Added smooth transform and shadow effects on hover
- Enhanced milestone cards with lift animation and emerald glow
- Improved user interaction in development milestones section
- Resolves #205

✨ [UI] Add hover effects to development milestones

---

package-lock.json
src/pages/PriceSection.jsx

Adjusted the positioning of the 'Most Popular' badge within the pricing card to ensure proper alignment and consistent layout across all screen sizes. Previously, the badge overflowed and hidden from top.
issue #284 
Fixes #
-[ ] 🐛 Bug Fix
-[ ] 🎨 UI/UX Improvement
---
-Updated CSS for pricing card badge positioning.
-Tested alignment on mobile and desktop views.
-Ensured consistent spacing and visual hierarchy with other cards.
---
- [✅] My code follows the project’s coding guidelines
- [✅] I have tested these changes locally
- [✅] No new warnings or errors introduced
- [✅] I have checked for and resolved merge conflicts
---
https://drive.google.com/file/d/14t-Kj69y-0grjnRukqDD2tGsgSTZ2G7e/view?usp=sharing
---
Badge now sits correctly on top-right of pricing card without overlapping and …

Fix: Adjust 'Most Popular' badge positioning within pricing card

---

backend/controllers/messageController.js
backend/server.js
package-lock.json

Fixed the registration issue where users were unable to sign up using Google Sign-In due to Auth/Unauthorized-domain error.
Also improved input validation on the registration form to ensure correct email formats and stronger passwords.
Fixes #238
---
1.  Fixed Google Sign-In flow to allow successful registration.
2.  Added front-end validation for email format.
3.  Improved password validation for stronger security.
4.  Updated error messages for better user feedback.
---
---
Before: Registration failed when using Google Sign-In.
[
](url)
After: Users can now successfully register using Google authentication.
---
This PR resolves the Google Sign-In issue (#238) and ensures smoother registration with proper validation.

Auth/Unauthorized-domain on Google Sign-In #238

---

src/pages/auth/ForgotPassword.jsx

This PR adds the site's global navbar and footer components to the forgot-password page for improved layout consistency and a more cohesive user experience.
Fixes #297
---
1. Imported and rendered the Navbar component at the top of the page.
2. Imported and rendered the Footer component at the bottom.
3. Adjusted layout and spacing to maintain a clean structure with the new components.
4. Verified styling matches the look and feel of the rest of the site.
---
---
---
Please assign and add labels

Add Navbar and Footer to Forgot Password Page

---

README.md
package-lock.json
src/pages/LandingPage.jsx

Added missing and meaningful `alt` attributes to project images for better accessibility.  
This improves screen reader support and makes the project more inclusive.
---
1. Added descriptive `alt` text to contributors image.  
2. Added meaningful `alt` text to GitHub badges (stars, forks, etc.).  
---
---
N/A (documentation change only)
---
This PR resolves the accessibility issue related to missing `alt` attributes in project images.

Added missing alt attributes and minor changes

---

package-lock.json
package.json
src/pages/Testimonials.jsx

hello!
this PR enhances the testimonial section animation in the landing page.
Fixes #304 
Contributor Information:
Name: Suranjana Paul
Email ID: paulsuranjana64@gmail.com
Type of Change: UI/UX improvement
the changes made are:
1. the previous animation of the cards were not looking proper and were hard to navigate. i have changed that and added a smooth, easy to access slider animation using React Slick. now it is easier to navigate for the user!
2. the quotation marks were not properly placed and looked wonky, i fixed them so that they look good.
https://github.com/user-attachments/assets/1b6e1fd8-a4ba-4af8-a352-b7d0d86e550a
all changes have been tested and reviewed to ensure functionality. i’d love your feedback and am happy to make further adjustments if needed. thanks for the …

Enhanced the testimonial section animation

---

src/pages/Blog.jsx

Enhanced the Blog page to improve usability and prepare for future detailed blog pages.
- Added a **search bar** to filter blog posts by title or author.
- Added **'Read More' links** under each blog card.
- Display a **friendly message** when no posts match the search query.
- Improves user experience by making it easier to find relevant blog posts.
- Prepares the Blog page for future integration with individual blog detail pages.
- Maintains consistency with existing UI and dark mode support.
- No backend changes required; purely front-end enhancement.
- Responsive design tested on desktop and mobile viewports.

✨ [Feature Add] Added search bar and 'Read More' links to Blog page

---

src/components/common/Navbar.jsx

- Used Tailwind’s responsive utilities (sm:, md:, lg:) to adjust layout.
- Ensured media queries are working correctly.
- Improved spacing/padding for better touch experience.
- Only ```Navbar.jsx``` has been modified.
- **Improvements include**:
1). Mobile menu now fades smoothly and scrolls correctly to section targets (e.g., #pricing).
2). On auth pages (Sign in/Sign up), only Home, Sign in, and Sign up are displayed for clarity.

Navbar Responsiveness Fixed (issue #330)

---

dev-dist/sw.js
src/App.css
src/App.jsx
src/components/common/CursorBurst.jsx

This PR introduces an engaging cursor burst effect with different colors  and particles that follows the user's mouse movements. The effect enhances user experience with a visually appealing interaction while maintaining the application's professional healthcare focus.
Issue #337 
Fixes #  https://drive.google.com/file/d/1-V-RXaNZtI_Nq-WkRlAEau99JkFnYgZl/view?usp=drivesdk
---
Files Modified
App.jsx - Integrated the CursorBurst component with conditional rendering
CursorBurst.jsx - New component implementing the cursor effect
tailwind.config.js - Added custom animation utilities
---

Added Cursor Burst Effect

---

backend/config/db.js
backend/controllers/authController.js
backend/controllers/messageController.js
backend/controllers/passwordResetController.js
backend/controllers/socketController.js
backend/db/models/Conversation.js
backend/db/models/Doctor.js
backend/db/models/Message.js
backend/db/models/PasswordReset.js
backend/db/models/User.js
backend/db/seed.js
backend/middleware/auth.js
backend/middleware/error.js
backend/middleware/validation.js
backend/package.json
backend/routes/authRoutes.js
backend/routes/messageRoutes.js
backend/server.js

Converted CommonJS into ES module as it is older and es module are new and modern
Fixes #331 
- [✔️ ] ♻️ Code Refactoring
---
1. Removed old CommonJS imported file
2. set type: module in package.json
3. Added ES module import/export in all files
---
- [✔️ ] My code follows the project’s coding guidelines
- [ ✔️] I have tested these changes locally
- [ ✔️] Documentation has been updated (if applicable)
- [✔️ ] No new warnings or errors introduced
- [ ✔️] I have checked for and resolved merge conflicts
---
before
After

Changed commonJS (require) to ES module (import/export)

---

README.md
dev-dist/sw.js

#358 
Updated the `README.md` to include the latest project structure and documentation improvements for better clarity and contributor guidance.
Fixes # (if applicable)
---
1. Updated `README.md` with new folder structure.
2. Improved documentation formatting and consistency.
3. Added detailed explanations for project setup and structure.
---
---
N/A
---
This update makes the repository more beginner-friendly and easier to navigate for contributors.

Folder Struture updated in README

---

src/pages/FAQSection.jsx

The Frequently Asked Questions section was static and lacked interactivity. I have enhanced the user experience by adding subtle hover effects to the FAQ cards, including slight translation and a fading border effect, making the section feel more dynamic and engaging.
Fixes #320 
---
1. Added a subtle hover effect to FAQ cards where the card slightly translates (moves) to give a sense of depth.
2. Applied a fading border effect on hover to enhance the visual interaction and improve user experience.
---
---
---
Email id: simranpreetk9305@gmail.com

📦 [UI/UX] Added Hover effect in FAQ cards

---

dev-dist/sw.js
package-lock.json
src/pages/Footer.jsx

This PR updates the outdated Twitter bird icon to the latest Twitter X logo throughout the pages for consistency with the current Twitter branding.
Screenshot:
Closes: #386 
@akathedeveloper

Updated Twitter Icon

---

src/components/common/CalendarModal.jsx

removed extrenal css and added tailwind css
Fixes #354 
---
1. changes calendermodal.jsx css to tailwind css
2. 
3. 
---
---
---

fixed calender model.jsx 

---

dev-dist/sw.js
package-lock.json
package.json
src/pages/auth/Login.jsx

This PR fixes the login and Google login redirect issue.
After successful authentication, users are now redirected to /home instead of /.
Fixes #
1. redirect to /home

Fix: Redirect user to /home after login success

---

dev-dist/sw.js
src/pages/PriceSection.jsx

📝 Description
Added authentication-based redirect functionality to the pricing section's "Start Free Trial" buttons. When users click these buttons without being logged in, they are now automatically redirected to the registration page to create an account before accessing trial features.
🔗 Related Issue(s)
Fixes #366 
📄 Type of Change
🚀 New Feature
🐛 Bug Fix
📝 Documentation Update
♻️ Code Refactoring
🎨 UI/UX Improvement
⚡ Performance Optimization
✅ Test Addition/Update
📋 Changes Made
Added authentication check logic to pricing section buttons
Implemented redirect functionality to registration page for unauthenticated users
Enhanced user flow by preventing access to trial features without proper authentication
✅ Checklist
My code follows the project's coding guidelines
I have tested these …

free trail navigating to register'

---

dev-dist/sw.js
src/locales/en.json
src/pages/auth/Register.jsx

Added validation in the registration form to make the "Terms and Conditions" checkbox mandatory before form submission.  
This ensures users cannot register without agreeing to the terms.
Fixes #249
---
1. Added required validation for the "Terms and Conditions" checkbox.  
2. Updated form submission logic to block submission until the checkbox is checked.  
3. Displayed error message if the user tries to submit without checking it.  
---
---
---
None

enhance: made terms checkbox compuslory

---

dev-dist/sw.js
src/components/common/CalendarModal.jsx

Added a schedule button on which click shows a popup of successful message with date
Fixes #421 
---
1. added a schedule button
2. added a popup after scheduling demo
3. 
---
---
before change
After change
---

adding schedule button

---

dev-dist/sw.js
src/pages/FAQSection.jsx

…ction (Fixes #433)
This PR refactors the FAQ section into a horizontally scrolling, responsive carousel component to improve discoverability and reduce vertical scrolling. The centered card is visually emphasized via scale/shadow/opacity transitions for clearer focus. The component supports keyboard navigation, dot pagination and smooth centering on click.
Fixes #433
---
1. Replaced `src/pages/FAQSection.jsx` with a horizontal, scroll-snap carousel implementation (Tailwind + React).  
2. Added responsive `min-width` CSS breakpoints so ~1 card (mobile), ~2 (small), ~3 (tablet) and ~4 (desktop) are visible.  
3. Implemented scroll-tracking to detect the center/active card and smooth centering on click.  
4. Added keyboard navigation (Left/Right arrows), left/right arrow buttons (desktop), …

Feat(UI): Implement responsive, animated horizontal carousel for FAQ section
